version: 2.1
jobs:
  build:
    working_directory: ~/digdag-slack
    docker:
      - image: cimg/openjdk:8.0.402
        environment:
         TERM: dumb

    steps:
      - checkout
      - run: ./gradlew clean && ./gradlew publish

      - run:
          name: Install digdag
          command: |
            sudo curl -o /bin/digdag --create-dirs -L "https://dl.digdag.io/digdag-latest"
            sudo chmod +x /bin/digdag

      - run:
          name: Testing post to slack
          command: |
            cd .circleci
            rm -rf .digdag/plugins
            ./test.sh
          environment:
            version: 0.1.5-SNAPSHOT
