---
username: Digdag
icon_emoji: ':cry:'
attachments:
- fallback: '[FAILED] ${workflow_name} workflow'
  color: "danger"
  text: '*[FAILED]* `${workflow_name}` Workflow'
  mrkdwn_in:
  - text
  - pretext
  - fields
  fields:
  - title: Task Name
    value: "${task_name}"
    short: false
  - title: Error Message
    value: "`${error.message}`"
    short: false
  - title: Session Date
    value: "${session_date}"
    short: true
  - title: Environment
    value: "${ENV}"
    short: true